---
- hosts: all
  vars:
    lacave_root_pem_file: resources/cert/lacave-root.pem
    os_cert_dest: /etc/pki/ca-trust/source/anchors
    os_ca_update_command: update-ca-trust
    kubernetes_cert_dir: /etc/kubernetes/ssl
  tasks:
  - name: Copier le certificat dans le magasin OS
    copy:
      src: "{{ lacave_root_pem_file }}"
      dest: "{{ os_cert_dest }}"
  - name: installer le cerificat
    command: "{{ os_ca_update_command }}"
  - name: Créer le répertoire certificats kubernetes
    file:
      dest: "{{ kubernetes_cert_dir }}"
      state: directory
  - name: Copier le certificat pour kubernetes
    copy:
      src: "{{ lacave_root_pem_file }}"
      dest: "{{ kubernetes_cert_dir }}"