- hosts: management
  vars:
    helm_install_url: https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz
    cert_manager_manifest_url: https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
    pgo_version: v4.5.1
    pgo_repository_base_url: https://raw.githubusercontent.com/CrunchyData/postgres-operator
    pgo_client_url: "{{ pgo_repository_base_url }}/{{ pgo_version }}/installers/kubectl/client-setup.sh"
    pgo_manifest_url: "{{ pgo_repository_base_url }}/{{ pgo_version }}/installers/kubectl/postgres-operator.yml"
    eck_manifest_url: "https://download.elastic.co/downloads/eck/{{ eck_version | default('1.2.1') }}/all-in-one.yaml"
  tasks:
  - name: Installer le module Kubernetes pour Python3
    apt:
      name: python3-kubernetes
      state: present
    when: ansible_os_family == "Debian"
  - name: Installer les packages Python
    pip:
      name: openshift
      extra_args: --user
      state: present
  - name: Créer le répertoire pour la configuration de kubectl
    file:
      dest: "{{ ansible_env.HOME }}/.kube"
      state: directory
  - name: Copier le fichier qui contient le crédentiel Admin
    copy:
      src: inventory/lacave/artifacts/admin.conf
      dest: "{{ ansible_env.HOME }}/.kube/config"
  - name: Installer Helm
    snap:
      classic: yes
      name: helm
      state: present
  - name: Installer le référentiel stable de Helm
    community.kubernetes.helm_repository:
      name: stable
      repo_url: "https://charts.helm.sh/stable"
      state: present
  - name: Creer l'utilisateur admin pour le tableau de bord Kubernetes
    k8s:
      state: present
      definition: "{{ lookup('file','resources/dashboard-adminuser.yml') }}"    
  - name: Deployer Cert-Manager
    include_tasks: resources/cert/deploy_cert_manager.yml
  - name: Déployer l'Ingress pour le registre Interne
    k8s:                                                                                                                                                                                                             
      state: present
      definition: "{{ lookup('template','resources/ingress/registry-ingress-manifest.yaml.j2') }}"
  - name: Deployer Rook-CEPH
    include_tasks: resources/rook/deploy_rook.yml
  - name: Deployer Monitoring
    include_tasks: resources/monitoring/deploy_monitoring.yml
  - name: Deployer Nexus
    include_tasks: resources/nexus/deploy_nexus.yml
  - name: Deployer ECK
    include_tasks: resources/journalisation/deploy_eck.yml
  - name: Deployer Graylog
    include_tasks: resources/journalisation/deploy_graylog.yml
  - name: Deployer l'opérateur Postgres
    include_tasks: resources/crunchy/deploy_pgo.yml
  #- name: Deployer Keycloak
  #  include_tasks: resources/keycloak/deploy_keycloak.yml
  - name: Afficher le mot de passe Dashboard CEPH
    debug:
      var: rook_ceph_dashboard_password
  - name: Afficher le mot de passe Elastic pour ECK
    debug:
      var: eck_elastic_password
  - name: Afficher le mot de passe admin pour Graylog
    debug:
      var: graylog_password