---
- name: Obtenir la configuration actuelle des Inputs
  uri:
    url: "{{ graylog_url }}/api/system/inputs"
    user: "admin"
    password: "{{ graylog_password }}"
    return_content: yes
    method: GET
    status_code: 200
  register: graylog_inputs

- name: Configuration de l'input Beats
  uri:
    url: "{{ graylog_url }}/api/system/inputs"
    user: "admin"
    password: "{{ graylog_password }}"
    method: POST
    headers:
      X-Requested-By: "Admin"
    body: "{{ lookup('template','input-beats-settings.json.j2') }}"
    body_format: json
    status_code: 201
  when:
  - "'beats' not in graylog_inputs.content"
  
- name: Configuration de l'input Gelf TCP
  uri:
    url: "{{ graylog_url }}/api/system/inputs"
    user: "admin"
    password: "{{ graylog_password }}"
    method: POST
    headers:
      X-Requested-By: "Admin"
    body: "{{ lookup('template','input-gelf-settings.json.j2') }}"
    body_format: json
    status_code: 201
  when:
  - "'gelf-tcp' not in graylog_inputs.content"

  
- name: Configuration de l'input Gelf UDP
  uri:
    url: "{{ graylog_url }}/api/system/inputs"
    user: "admin"
    password: "{{ graylog_password }}"
    method: POST
    headers:
      X-Requested-By: "Admin"
    body: "{{ lookup('template','input-gelf-udp-settings.json.j2') }}"
    body_format: json
    status_code: 201
  when:
    - "'gelf-udp' not in graylog_inputs.content"

- name: Configuration de l'input Syslog
  uri:
    url: "{{ graylog_url }}/api/system/inputs"
    user: "admin"
    password: "{{ graylog_password }}"
    method: POST
    headers:
      X-Requested-By: "Admin"
    body: "{{ lookup('template','input-syslog-settings.json.j2') }}"
    body_format: json
    status_code: 201
  when:
    - graylog_syslog_input is defined
    - graylog_syslog_input | bool
    - "'syslog-tcp' not in graylog_inputs.content"
