---
- name: Obtenir l'ID du noeud à configurer
  uri:
    url: "http://{{ ansible_hostname }}:{{ graylog_port_http }}/api/system/cluster/node"
    user: "{{ graylog_admin }}"
    password: "{{ graylog_admin_password }}"
    return_content: yes
  register: graylog_nodeinfo
  until: graylog_nodeinfo.status == 200
  retries: 3
  delay: 30

- debug:
    msg: "Node id trouvée: {{ graylog_nodeinfo.json.node_id }}."

- name: Configuration LDAP
  uri:
    url: "http://{{ ansible_hostname }}:{{ graylog_port_http }}/api/system/ldap/settings"
    user: "{{ graylog_admin }}"
    password: "{{ graylog_admin_password }}"
    method: PUT
    headers:
      X-Requested-By: "Jenkins"
    body: "{{ lookup('template','ldap-settings.json.j2') }}"
    body_format: json
    status_code: 200,201,204
  register: config_ldap
  until: config_ldap.status == 200 or config_ldap.status == 201 or config_ldap.status == 204
  retries: 3
  delay: 30
  when: graylog_ldap_uri is defined and ldap_user_search_base is defined and ldap_group_search_base is defined and ldap_admin_group_mapping is defined

- name: Obtenir la configuration actuelle des Inputs
  uri:
    url: "http://{{ ansible_hostname }}:{{ graylog_port_http }}/api/system/inputs"
    user: "{{ graylog_admin }}"
    password: "{{ graylog_admin_password }}"
    return_content: yes
    method: GET
    status_code: 200
  register: graylog_inputs

- name: Configuration de l'input Beats
  uri:
    url: "http://{{ ansible_hostname }}:{{ graylog_port_http }}/api/system/inputs"
    user: "{{ graylog_admin }}"
    password: "{{ graylog_admin_password }}"
    method: POST
    headers:
      X-Requested-By: "Jenkins"
    body: "{{ lookup('template','input-beats-settings.json.j2') }}"
    body_format: json
    status_code: 201
  when:
    - graylog_beats_input is defined
    - graylog_beats_input | bool
    - "'beats' not in graylog_inputs.content"

- name: Configuration de l'input Gelf TCP
  uri:
    url: "http://{{ ansible_hostname }}:{{ graylog_port_http }}/api/system/inputs"
    user: "{{ graylog_admin }}"
    password: "{{ graylog_admin_password }}"
    method: POST
    headers:
      X-Requested-By: "Jenkins"
    body: "{{ lookup('template','input-gelf-settings.json.j2') }}"
    body_format: json
    status_code: 201
  when:
    - graylog_gelf_input is defined
    - graylog_gelf_input | bool
    - "'gelf-tcp' not in graylog_inputs.content"

- name: Configuration de l'input Gelf UDP
  uri:
    url: "http://{{ ansible_hostname }}:{{ graylog_port_http }}/api/system/inputs"
    user: "{{ graylog_admin }}"
    password: "{{ graylog_admin_password }}"
    method: POST
    headers:
      X-Requested-By: "Jenkins"
    body: "{{ lookup('template','input-gelf-udp-settings.json.j2') }}"
    body_format: json
    status_code: 201
  when:
    - graylog_gelf_input is defined
    - graylog_gelf_input | bool
    - "'gelf-udp' not in graylog_inputs.content"

- name: Configuration de l'input Syslog
  uri:
    url: "http://{{ ansible_hostname }}:{{ graylog_port_http }}/api/system/inputs"
    user: "{{ graylog_admin }}"
    password: "{{ graylog_admin_password }}"
    method: POST
    headers:
      X-Requested-By: "Jenkins"
    body: "{{ lookup('template','input-syslog-settings.json.j2') }}"
    body_format: json
    status_code: 201
  when:
    - graylog_syslog_input is defined
    - graylog_syslog_input | bool
    - "'syslog-tcp' not in graylog_inputs.content"
