---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: login-kube-lacave-tls
  namespace: kube-system
spec:
  secretName: login-kube-lacave-tls
  issuerRef:
    name: ca-lacave-issuer
    kind: ClusterIssuer
  commonName: login.kube.lacave
  organization:
  - Lacave CA
  dnsNames:
  - login.kube.lacave
  - login.kube.lacave.info
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: login-lacave
  namespace: kube-system
  labels:
    app: login-lacave
spec:
  serviceName: login-lacave
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    #rollingUpdate:
    #  maxSurge: 1
    #  maxUnavailable: 1
  selector:
    matchLabels:
      app: login-lacave
  template:
    metadata:
      labels:
        app: login-lacave
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: keycloak
        image: docker.lacave.info/lacave/keycloak:10.0.2
        imagePullPolicy: Always
        env:
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: postgres
        - name: KEYCLOAK_DB_DRIVER
          value: postgresql
        - name: DB_URL
          value: "jdbc:postgresql://loginlacavecluster.kcdatabases:5432/keycloak"
        - name: DB_ADDR
          value: loginlacavecluster.kcdatabases
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: keycloak
        - name: DB_SCHEMA
          value: keycloak
        - name: DB_USER
          value: keycloak
        - name: DB_USERNAME
          value: keycloak
        - name: DB_PASSWORD
          value: keycloak
        - name: KEYCLOAK_HA_CONFIG
          value: standalone-ha-lacave.xml
        - name: JGROUPS_DISCOVERY_PROTOCOL
          value: JDBC_PING
#        - name: JGROUPS_DISCOVERY_PROTOCOL
#          value: dns.PING
#        - name: JGROUPS_DISCOVERY_PROPERTIES
#          value: "dns_query=login-lacave-service"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
          failureThreshold: 30
          periodSeconds: 30
      securityContext:
        fsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: kube-system
  name: ingress-login-lacave
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: ca-lacave-issuer
spec:
  tls:
  - hosts:
    - login.kube.lacave
    - login.kube.lacave.info
    secretName: login-kube-lacave-tls
  rules:
  - host: login.kube.lacave
    http:
      paths:
      - path: /
        backend:
          serviceName: login-lacave-service
          servicePort: 8080
  - host: login.kube.lacave.info
    http:
      paths:
      - path: /
        backend:
          serviceName: login-lacave-service
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: login-lacave-service
  namespace: kube-system
  labels:
    app: login-lacave
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: login-lacave
