---
apiVersion: v1
kind: Namespace
metadata:
  name: unam
  labels:
    istio-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: unam
  name: unam-deployment
  labels:
    app: unam-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unam-service
  template:
    metadata:
      labels:
        app: unam-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: unam-service
        image: docker.lacave.info/inspq/utilitaire-nam-service:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: unam
  name: unam-service
  labels:
    serviceapp: actuator
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "28081"
spec:
  selector:
    app: unam-service
  ports:
    - name: web
      protocol: TCP
      port: 14101
      targetPort: 8080
    - name: actuator
      protocol: TCP
      port: 27082
      targetPort: 28081
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: unam
  name: unam-service
  labels:
    account: unam
    
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: unam
  name: ingress-unam
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: unam.lacave.info
    http:
      paths:
      - path: /
        backend:
          serviceName: unam-service
          servicePort: 14101
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: actuator
  labels:
    release: lacave-prom
spec:
  selector:
    matchLabels:
      serviceapp: actuator
  endpoints:
  - port: actuator
    path: '/actuator/prometheus'
    interval: 15s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: unam
  name: unamui-deployment
  labels:
    app: unam-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unam-ui
  template:
    metadata:
      labels:
        app: unam-ui
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: unam-ui
        image: docker.lacave.info/inspq/utilitaire-nam-uikubelacave:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: unam
  name: unam-ui
spec:
  selector:
    app: unam-ui
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: unam
  name: ingress-unam-ui
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: unamui.lacave.info
    http:
      paths:
      - path: /
        backend:
          serviceName: unam-ui
          servicePort: 80
