apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: db-svc-monitor
  namespace: monitoring
  labels:
    release: lacave-prom
spec:
  selector:
    matchLabels:
      pg-cluster: testcluster
  namespaceSelector:
    matchNames:
      - "pgo"
  endpoints:
  - port: postgres-exporter