---
login_keycloak_image: "{{ kube_registry_url }}/{{ project_name }}/keycloak"
login_keycloak_image_version: "{{ login_keycloak_version | default('11.0.3') }}"
login_keycloak_user: "{{ login_keycloak_admin_username | default('admin') }}"
login_keycloak_password: "{{ login_keycloak_admin_password | default('admin') }}"
login_keycloak_external_port: 18081
login_keycloak_protocol: https
login_keycloak_url: "{{ login_keycloak_protocol }}://{{ login_keycloak_base_url }}"
login_keycloak_auth_client_id: admin-cli
login_keycloak_auth_client_secret:
login_keycloak_auth_realm: master
login_keycloak_ha_config: standalone-ha-login.xml
login_keycloak_db_username: "{{ login_keycloak_db_username | default('admin') }}"
login_keycloak_db_password: "{{ login_keycloak_db_password | default('admin') }}"
login_keycloak_db_addr: "login{{ project_name }}cluster"
login_keycloak_db_port: 5432
login_keycloak_db_database: keycloak
login_keycloak_db_schema: keycloak
login_keycloak_db_driver: postgresql
login_keycloak_db_vendor: postgres
login_keycloak_db_url: "jdbc:{{ login_keycloak_db_driver }}://{{ login_keycloak_db_addr }}:{{ login_keycloak_db_port }}/{{ login_keycloak_db_database }}"
login_keycloak_graylog_host: "{{ project_name }}-graylog.graylog-system.svc"
login_keycloak_graylog_gelf_udp: "{{ graylog_gelf_udp_port | default(12231) }}"
login_keycloak_proxy_address_forwarding: "true"
kubernetes_realm: kubernetes
smtp_server: "smtp.{{ global_domain_name }}"

#Information sur les REALM
login_keycloak_realms: 
  - realm: "{{ kubernetes_realm }}"
    name: Kubernetes
    namehtml: "Kubernetes"
    loginTheme: "{{ login_keycloak_default_theme | default('keycloak') }}"
    adminTheme: "{{ login_keycloak_default_theme | default('keycloak') }}"
    emailTheme: "{{ login_keycloak_default_theme | default('keycloak') }}"
    accountTheme: "{{ login_keycloak_default_theme | default('keycloak') }}"
    bruteForceProtected: true
    loginWithEmailAllowed: false
    duplicateEmailsAllowed: true
    verifyEmail: false
    permanentLockout: false
    maxFailureWaitSeconds: 900
    minimumQuickLoginWaitSeconds: 60
    waitIncrementSeconds: 300
    quickLoginCheckMilliSeconds: 1000
    maxDeltaTimeSeconds: 21600
    failureFactor: 10
    supportedLocales:
      - fr
    defaultLocale: fr
    smtpserver:
      replyToDisplayName: root@localhost
      port: "25"
      host: "{{ smtp_server }}"
      replyTo: "root@localhost"
      from: "root@localhost"
      fromDisplayName: "root@localhost"
      envelopeFrom: "root@localhost"
    eventsConfig:
      eventsEnabled: true
      eventsListeners :
        - jboss-logging
      adminEventsEnabled: true
      eventsExpiration: 172800
      adminEventsDetailsEnabled: true

login_keycloak_idps: []
#  - alias: google
#    realm: "{{ kubernetes_realm }}"
#    displayName: "Connexion avec Google"
#    providerId: oidc
#    firstBrokerLoginFlowAlias: "Test first broker login"
#    postBrokerLoginFlowAlias: "Test post broker login"
#    config:
#      openIdConfigurationUrl: "{{ idp_openid_config_url }}"
#      clientId: "{{ idp_clientId }}"
#      clientSecret: "{{ idp_clientSecret }}"
#      disableUserInfo: True
#      defaultScope: "openid email profile"
#      guiOrder: "1"
#      backchannelSupported: True
#    mappers:
#      - name: GivenNameMapper
#        config:
#          claim: given_name
#          user.attribute: firstName
#      - name: FamilyNameMapper
#        config:
#          claim: family_name
#          user.attribute: lastName
#      - name: UsernameMapper
#        identityProviderMapper: oidc-username-idp-mapper
#        config:
#          template: "${CLAIM.upn}"

login_keycloak_roles:
  - name: cluster-admin
    realm: "{{ kubernetes_realm }}"
    description: "Administrateurs cluster Kubernetes"
    composite: false

login_keycloak_users:
  - auth_keycloak_url: "{{ login_keycloak_url }}"
    auth_keycloak_user: "{{ login_keycloak_user }}"
    auth_keycloak_password: "{{ login_keycloak_password }}"
    realm: "{{ kubernetes_realm }}"
    username: admin
    firstName: Admin
    lastName: Kubernetes
    email: "nobody@{{ kube_domain_name }}"
    enabled: true
    emailVerified: false
    credentials:
      - type: password
        value: "{{ login_keycloak_admin_password }}"
        temporary: false
    realmRoles:
      - cluster-admin
    state: present

login_keycloak_clients:
  - clientId: account
    auth_keycloak_url: "{{ login_keycloak_url }}"
    auth_keycloak_user: "{{ login_keycloak_user }}"
    auth_keycloak_password: "{{login_keycloak_password}}"
    realm: "{{ kubernetes_realm }}"
    defaultRoles:
      - cluster-admin

login_keycloak_client_scopes: []