---
## Ansible Settings CoreOS
#ansible_become: root
ansible_user: root
#ansible_become_user: root
ansible_python_interpreter: /usr/bin/python3

## Directory where etcd data stored
etcd_data_dir: /var/lib/etcd

## Experimental kubeadm etcd deployment mode. Available only for new deployment
etcd_kubeadm_enabled: false

## Directory where the binaries will be installed
bin_dir: /usr/local/bin

## The access_ip variable is used to define how other nodes should access
## the node.  This is used in flannel to allow other flannel nodes to see
## this node for example.  The access_ip is really useful AWS and Google
## environments where the nodes are accessed remotely by the "public" ip,
## but don't know about that address themselves.
# access_ip: 1.1.1.1


## External LB example config
## apiserver_loadbalancer_domain_name: "elb.some.domain"
# loadbalancer_apiserver:
#   address: 1.2.3.4
#   port: 1234

## Internal loadbalancers for apiservers
# loadbalancer_apiserver_localhost: true
# valid options are "nginx" or "haproxy"
# loadbalancer_apiserver_type: nginx  # valid values "nginx" or "haproxy"

## Local loadbalancer should use this port
## And must be set port 6443
loadbalancer_apiserver_port: 6443

## If loadbalancer_apiserver_healthcheck_port variable defined, enables proxy liveness check for nginx.
loadbalancer_apiserver_healthcheck_port: 8081

### OTHER OPTIONAL VARIABLES

## Upstream dns servers
# upstream_dns_servers:
#   - 8.8.8.8
#   - 8.8.4.4

## There are some changes specific to the cloud providers
## for instance we need to encapsulate packets with some network plugins
## If set the possible values are either 'gce', 'aws', 'azure', 'openstack', 'vsphere', 'oci', or 'external'
## When openstack is used make sure to source in the openstack credentials
## like you would do when using openstack-client before starting the playbook.
# cloud_provider:

## When cloud_provider is set to 'external', you can set the cloud controller to deploy
## Supported cloud controllers are: 'openstack' and 'vsphere'
## When openstack or vsphere are used make sure to source in the required fields
# external_cloud_provider:

## Set these proxy values in order to update package manager and docker daemon to use proxies
# http_proxy: ""
# https_proxy: ""

## Refer to roles/kubespray-defaults/defaults/main.yml before modifying no_proxy
# no_proxy: ""

## Some problems may occur when downloading files over https proxy due to ansible bug
## https://github.com/ansible/ansible/issues/32750. Set this variable to False to disable
## SSL validation of get_url module. Note that kubespray will still be performing checksum validation.
# download_validate_certs: False

## If you need exclude all cluster nodes from proxy and other resources, add other resources here.
# additional_no_proxy: ""

## If you need to disable proxying of os package repositories but are still behind an http_proxy set
## skip_http_proxy_on_os_packages to true
## This will cause kubespray not to set proxy environment in /etc/yum.conf for centos
# skip_http_proxy_on_os_packages: false

## Since workers are included in the no_proxy variable by default, docker engine will be restarted on all nodes (all
## pods will restart) when adding or removing workers.  To override this behaviour by only including master nodes in the
## no_proxy variable, set below to true:
no_proxy_exclude_workers: false

## Certificate Management
## This setting determines whether certs are generated via scripts.
## Chose 'none' if you provide your own certificates.
## Option is  "script", "none"
## note: vault is removed
# cert_management: script

## Set to true to allow pre-checks to fail and continue deployment
# ignore_assert_errors: false

## The read-only port for the Kubelet to serve on with no authentication/authorization. Uncomment to enable.
# kube_read_only_port: 10255

## Set true to download and cache container
# download_container: true

## Deploy container engine
# Set false if you want to deploy container engine manually.
# deploy_container_engine: true
project_name: lacave
global_domain_name: "{{ project_name }}.info"
kube_domain_name: "kube.{{ global_domain_name }}"
self_signed_pki_path: /home/felip/pki
self_signed_pki_key_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;lacave
          34373939393864666661386531613631363632636235393838623061373164333836316262323830
          6663663164663137333332306433303833323562656565660a643533323062356536386463623138
          64376261343032366462623831396362303264643563616333663737353635646163643332363262
          6362313362333330310a333764383937343630353465306565326432303465626634666136616636
          6535
nexus_admin_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;lacave
          39386135303762333863353231326461303831306237323235336666633538343539326230323538
          6530616138306634636265356134353563346234386264660a343238623430366635303033353831
          63356536333236386437623034353431613361613534666333323639616432613034613532396535
          3937313837643265650a396562616361323863663830373063646434316362613237626135356338
          6231
pgo_apiserver_forward_to_port: 18443
login_keycloak_db_username: !vault |
          $ANSIBLE_VAULT;1.2;AES256;lacave
          66623233396330636634636161353365626261663765393635653266666461646435346635383962
          3965386161323831663562336665353064643162363666370a633138313138396366383563386563
          39313832626337316536346662346232376137306631373932303963353031643162343662386131
          6261336463326462390a636663393432316238353462636565643766353936393462663434386438
          3936
login_keycloak_db_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;lacave
          35656663373234383634666263643266643663666333313537386135623239663133373435333461
          6239653463313431396665623437316132393361343937300a383164396133316163356661656432
          66386330613032353861313566613536356135663138613739313132396464376334363839656330
          6636656165333038610a363034616437643132313931333536626434306430303431396263333463
          35303633323439613232386537656633663063636362373031643336626362316437313265383633
          3362356334643037663932343831346133613363383464343334